export const REGISTER = "REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";

export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";

export const DELETE_PRODUCTS = "DELETE_PRODUCTS";
export const DELETE_PRODUCTS_SUCCESS = "DELETE_PRODUCTS_SUCCESS";
export const DELETE_PRODUCTS_FAIL = "DELETE_PRODUCTS_FAIL";

export const EDIT_PRODUCTS = "EDIT_PRODUCTS";
export const EDIT_PRODUCTS_SUCCESS = "EDIT_PRODUCTS_SUCCESS";
export const EDIT_PRODUCTS_FAIL = "EDIT_PRODUCTS_FAIL";

export const ADD_PRODUCTS = "ADD_PRODUCTS";
export const ADD_PRODUCTS_SUCCESS = "ADD_PRODUCTS_SUCCESS";
export const ADD_PRODUCTS_FAIL = "ADD_PRODUCTS_FAIL";

export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_CLEAR_ITEMS = "CART_RESET";
